// <auto-generated />
using System;
using FYFI.Repository.InMemory.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FYFI.Repository.InMemory.Migrations
{
    [DbContext(typeof(FYFIDbContext))]
    [Migration("20260422114216_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FYFI.Repository.InMemory.Model.FiOutlook", b =>
                {
                    b.Property<int>("FiOutlookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FiOutlookId"));

                    b.HasKey("FiOutlookId");

                    b.ToTable("FiOutlooks");
                });

            modelBuilder.Entity("FYFI.Repository.InMemory.Model.FiOutlookYear", b =>
                {
                    b.Property<int>("FiOutlookYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FiOutlookYearId"));

                    b.Property<decimal>("Cash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FiOutlookId")
                        .HasColumnType("int");

                    b.Property<int>("YearDate")
                        .HasColumnType("int");

                    b.HasKey("FiOutlookYearId");

                    b.HasIndex("FiOutlookId");

                    b.ToTable("FiOutlookYears");
                });

            modelBuilder.Entity("FYFI.Repository.InMemory.Model.FiOutlookYear", b =>
                {
                    b.HasOne("FYFI.Repository.InMemory.Model.FiOutlook", null)
                        .WithMany("FiOutlookYears")
                        .HasForeignKey("FiOutlookId");
                });

            modelBuilder.Entity("FYFI.Repository.InMemory.Model.FiOutlook", b =>
                {
                    b.Navigation("FiOutlookYears");
                });
#pragma warning restore 612, 618
        }
    }
}
